[package]
name = "ai-rpa-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "ai_rpa_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
ai-rpa-node = { path = "../../../crates/node" }
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tokio.workspace = true
